### PR TITLE
Add emulated win-arm64 packs

### PR DESCRIPTION
**Pull request by lewing**

### CODE REVIEW

**Comment by lewing** [comment]
looks like this is confusing the packaging steps a bit

**Comment by lewing** [comment]
@joeloff just a heads up that this is something we may need to be able to package as well, it's reusing the same pack for win-x64 and win-arm64 which seems to be confusing the tooling

**Comment by joeloff** [comment]
I tested locally and it's finding all the files. The change seems fine as we should be extracting the package content once and then harvesting it multiple times for the different MSI flavors we produce.

**Comment by joeloff** [comment]
It's literally missing a few files in what appears to be random folders. I'll take a look at the bin logs and see if anything useful is logged.

**Comment by joeloff** [comment]
OK, this is odd, it seems to be extracting the packages multiple times while building, which can explain why some files are disappearing.

**Comment by joeloff** [comment]
Think I know what's happening. You need to use Arcade 7.0.0-beta.22106.1 or later (that has the fix to dedupe packages and is the issue you're running into right now)

**Comment by lewing** [comment]
I hadn't noticed main didn't have the arcade bump yet. Sorry for the noise

**Comment by akoeplinger** [comment]
main should have latest arcade now: https://github.com/dotnet/emsdk/pull/110

**Review by steveisok — APPROVED** [review]

**Pull request merged**
