### PR TITLE
Update llvm deps

### PR DESCRIPTION
**Pull request by radekdoulik**

### CODE REVIEW

**Comment by radekdoulik** [comment]
@akoeplinger do you know why the new llvm packages are not flowing through dotnet-maestro to emsdk?

**Comment by akoeplinger** [comment]
The subscription is set to EveryWeek so it just wasn't triggered yet, I triggered it manually and that worked: https://github.com/dotnet/emsdk/pull/1016

**Comment by radekdoulik** [comment]
> The subscription is set to EveryWeek (we normally don't have time critical changes) so it just wasn't triggered yet, I triggered it manually and that worked: #1016

great, thanks. where could I trigger it manually next time?

**Comment by akoeplinger** [comment]
`darc trigger-subscriptions --ids b7b658f3-33f7-49d1-e9cf-08db9342e1a4`

The subscription id is shown in the update PR, or you can get it with `darc get-subscriptions --source-repo llvm-project --target-repo emsdk`

**Pull request closed without merging**
