### PR TITLE
[release/6.0] Stop publishing 6.0.200 sdk band and bump release version

### PR DESCRIPTION
**Pull request by lewing**
staging this for october, if it needs to go in sooner remove the version bump

### CODE REVIEW

**Review by mmitche — APPROVED** [review]

**Comment by lewing** [comment]
@mmitche is it ok to land the for oct now?

**Comment by mmitche** [comment]
> @mmitche is it ok to land the for oct now?

Nope, it's perfect once branding is updated in this repo.

**Comment by carlossanlop** [comment]
@lewing I think this PR was submitted around the time the CI went down for maintenance. There are only 5 legs executed. I'll close and reopen this to rebase+retrigger CI.

**Comment by carlossanlop** [comment]
Ah... I think 5 legs are normal in this repo. Oh well. It shouldn't take too long.

I assume this is blocking https://github.com/dotnet/runtime/pull/74595?

**Comment by steveisok** [comment]
> Ah... I think 5 legs are normal in this repo. Oh well. It shouldn't take too long.
> 
> I assume this is blocking [dotnet/runtime#74595](https://github.com/dotnet/runtime/pull/74595)?

Yes, it's gotta go first before the runtime one can land.

**Comment by lewing** [comment]
> > @mmitche is it ok to land the for oct now?
> 
> Nope, it's perfect once branding is updated in this repo.

This includes the branding change, should I split it out?

**Pull request merged**
