### PR TITLE
Merge emscripten 3.1.1

### PR DESCRIPTION
**Pull request by radekdoulik**
Also revert 2.0.34 commit as it was squashed by mistake and re-merge the 2.0.34 PR branch again, before merging 3.1.1

### CODE REVIEW

**Comment by radekdoulik** [comment]
It should be merged or rebased without squashing, to allow smooth merge of upstream in future.

**Comment by lewing** [comment]
Lets get links to the staged prs in dotnet/icu and dotnet/runtime here then we can try rolling forward

**Comment by radekdoulik** [comment]
dotnet/icu PR: https://github.com/dotnet/icu/pull/183
dotnet/runtime PR: https://github.com/dotnet/runtime/pull/63894

**Review by lewing — APPROVED** [review]
Let's try this again.

**Pull request merged**
