### PR TITLE
Add prerelease label to the emsdk manifest

### PR DESCRIPTION
**Pull request by steveisok**
This is so the SDK can isolate vs what we'll ship with.

### CODE REVIEW

**Comment by steveisok** [comment]
Official build passes https://dev.azure.com/dnceng/internal/_build/results?buildId=2095288&view=results

**Review by lewing — COMMENTED** [review]
Should we label the new one Current from the start?

**Comment by akoeplinger** [comment]
Why not name it .net8 from the start? Then we don't need to do renaming later on

**Comment by steveisok** [comment]
> Why not name it .net8 from the start? Then we don't need to do renaming later on

It's easier to have a current that way you don't have to remember to PR to the installer for every new .NET.  That's where the baseline manifests need to end up.

**Review by lewing — APPROVED** [review]

**Comment by akoeplinger** [comment]
But don't we have to do that anyway once we're on net9 and need to have a net8 manifest? Maybe I'm misunderstanding how these flow 😄

**Comment by lewing** [comment]
@akoeplinger it's just that right at switchover the contents of current that will change are really just a few template items whereas the downlevel ones are more similar to each so the history is a lot cleaner, also Current would have kept the depency flow work but now with the prerelease stuff that is a pipedream

**Pull request merged**
