### PR TITLE
Add emulated packs for win-arm64

### PR DESCRIPTION
**Pull request by lewing**

### CODE REVIEW

**Comment by joeloff** [comment]
To build arm-64, we need to update this

https://github.com/dotnet/runtime/blob/782aa155d4fd7d84728091bd9b9da54c4f6ac161/src/workloads/workloads.csproj#L139

and separate out the manifest packages that flow to VS that supports arm64, then add the necessary metadata, something like

```xml
<ManifestPackages Include="$(PackageSource)Microsoft.NET.Workload.Mono.ToolChain.6.0-6.0.300.Manifest-*.nupkg" MsiVersion="$(MsiVersion)"/>
<ManifestPackages Include="$(PackageSource)Microsoft.NET.Workload.Mono.ToolChain.6.0-6.0.900*Manifest-*.nupkg" MsiVersion="$(MsiVersion)" SupportsMachineArch="true" />
```

Also, we need to make sure Arcade/main has all the updates we made in 6.0 and 7.0. I'll check to see if those changes were merged to Arcade/main.

**Comment by steveisok** [comment]
As it relates to emsdk, what should I put here?  The version numbers in your example are tripping me up because they are auto-generated.

https://github.com/dotnet/emsdk/blob/52e3130a816a7c8d734f1e9f0dc9ed6d5936e7ae/eng/workloads/workloads.csproj#L77-L79

**Comment by joeloff** [comment]
> As it relates to emsdk, what should I put here? The version numbers in your example are tripping me up because they are auto-generated.
> 
> https://github.com/dotnet/emsdk/blob/52e3130a816a7c8d734f1e9f0dc9ed6d5936e7ae/eng/workloads/workloads.csproj#L77-L79

Sorry, the example was a bit contrived. In the release branches we define all the feature bands in eng\versions.props. I was thinking perhaps we add the information explicitly. Again, this is just an example

```xml
  <!-- Expand the items in versions.props -->
  <ItemGroup>
    <WorkloadSdkBandVersions Include="6.0.100" SupportsMachineArch="true"/>
    <WorkloadSdkBandVersions Include="6.0.300" SupportsMachineArch="false"/>
    <WorkloadSdkBandVersions Include="6.0.400" SupportsMachineArch="true"/>
  </ItemGroup>
  
  <!-- In workload props, import the manifests packages based on the defined feature band versions,
but ignore the runtime version and set the SupportsMachineArch metadata accordingly -->
  <Target Name="L">
    <ItemGroup>
      <F Include="Microsoft.NET.Workload.Emscripten.Manifest-%(WorkloadSdkBandVersions.Identity)" SupportsMachineArch="%(SupportsMachineArch)" />
    </ItemGroup>    
    <Message Text="%(F.Identity), SupportsMachineArch: %(SupportsMachineArch)" />
  </Target>
```

**Review by joeloff — APPROVED** [review]

**Comment by steveisok** [comment]
Good official build https://dev.azure.com/dnceng/internal/_build/results?buildId=2014692&view=results

**Pull request merged**
